version: '3'

services:
    api:
        image: annaworks/chatservice:latest
        env_file:
            - .env
        build: 
            context: ./
            dockerfile: Dockerfile
            args: 
                PORT: "${API_PORT}"
        ports: 
            - "${API_PORT}:${API_PORT}"
        environment:
            API_PORT: "${API_PORT}"
            SLACK_TOKEN: "${SLACK_TOKEN}"
            SLACK_VERIFICATION_TOKEN: "${SLACK_VERIFICATION_TOKEN}"
            